{
	"version": 1546122037,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/jugador-sheet0.png",
		"images/jugador-sheet1.png",
		"images/jugador-sheet2.png",
		"images/bloqueo.png",
		"images/lata-sheet0.png",
		"images/lata-sheet1.png",
		"images/sistema-sheet0.png",
		"images/borganico-sheet0.png",
		"images/floresecerrad.png",
		"images/taruca-sheet0.png",
		"images/taruca-sheet1.png",
		"images/bloquelimite.png",
		"images/culibriyellow-sheet0.png",
		"images/caminoacasa-sheet0.png",
		"images/casa3sistema-sheet0.png",
		"images/cerronevado-sheet0.png",
		"images/arbolsisteam-sheet0.png",
		"images/arbol-sheet0.png",
		"images/aguilasistema-sheet0.png",
		"images/murcielsistema-sheet0.png",
		"images/lago2-sheet0.png",
		"images/gaviotasistema-sheet0.png",
		"images/lago-sheet0.png",
		"images/venadosistema-sheet0.png",
		"images/pumasistema-sheet0.png",
		"images/floramarsistema-sheet0.png",
		"images/colibrisistema-sheet0.png",
		"images/fox-sheet0.png",
		"images/vacasistem-sheet0.png",
		"images/perrosistema-sheet0.png",
		"images/ninio-sheet0.png",
		"images/ranasistema-sheet0.png",
		"images/btnjugar-sheet0.png",
		"images/punterobio-sheet0.png",
		"images/caminoacasa2-sheet0.png",
		"images/cerronevado2-sheet0.png",
		"images/arbol2-sheet0.png",
		"images/casa3sistema2-sheet0.png",
		"images/lago3-sheet0.png",
		"images/lagobio-sheet0.png",
		"images/floressistema-sheet0.png",
		"images/floramarsistema2-sheet0.png",
		"images/lagunsistema-sheet0.png",
		"images/arbol3-sheet0.png",
		"images/cerrar-sheet0.png",
		"images/puerta11-sheet0.png",
		"images/puerta11-sheet1.png",
		"images/sprite-sheet0.png",
		"images/pastlicoazu-sheet0.png",
		"images/papelarruinado-sheet0.png",
		"images/windo1-sheet0.png",
		"images/bonificarlo1.png",
		"images/cascarasnar-sheet0.png",
		"images/botellap-sheet0.png",
		"images/cascaraplatan-sheet0.png",
		"images/plasticovac-sheet0.png",
		"images/plasticdf-sheet0.png",
		"images/latalata-sheet0.png",
		"images/botellita-sheet0.png",
		"images/murcielsistema2-sheet0.png",
		"images/arbol4-sheet0.png",
		"images/aguilasistema2-sheet0.png",
		"images/venadosistema2-sheet0.png",
		"images/pumasistema2-sheet0.png",
		"images/ranasistema2-sheet0.png",
		"images/colibrisistema2-sheet0.png",
		"images/vacasistem2-sheet0.png",
		"images/perrosistema3-sheet0.png",
		"images/gaviotasistema2-sheet0.png",
		"images/cinco-sheet0.png",
		"images/restart-sheet0.png",
		"images/restart-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tile1.png",
		"images/sombranegro1.png",
		"images/tiempo1.png",
		"images/juegoterminado1-sheet0.png",
		"images/juegoterminado1-sheet1.png",
		"images/tilemapnivel1.png",
		"images/tilemapbloqueom1.png",
		"images/nextlevel1-sheet0.png",
		"images/nextlevel1-sheet1.png",
		"images/cerronevado3-sheet0.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnparlante-sheet0.png",
		"images/btnparlante-sheet1.png",
		"images/btnmusic2-sheet0.png",
		"images/btnparlante2-sheet0.png",
		"images/btnparlante2-sheet1.png",
		"images/casa1-sheet0.png",
		"images/casa1-sheet1.png",
		"images/button_2-sheet0.png",
		"images/button_2-sheet1.png",
		"images/casa2-sheet0.png",
		"images/casa2-sheet1.png",
		"images/casa3-sheet0.png",
		"images/casa3-sheet1.png",
		"images/btnjugar2-sheet0.png",
		"images/botonrojosalir-sheet0.png",
		"images/titulo1.png",
		"images/titulo2.png",
		"images/perro-sheet0.png",
		"images/perro-sheet1.png",
		"images/colibri-sheet0.png",
		"images/colibri-sheet1.png",
		"images/colibri-sheet2.png",
		"images/vaca-sheet0.png",
		"images/vaca-sheet1.png",
		"images/venado-sheet0.png",
		"images/venado-sheet1.png",
		"images/zorro-sheet0.png",
		"images/rana-sheet0.png",
		"images/rana-sheet1.png",
		"images/puma-sheet0.png",
		"images/aguila-sheet0.png",
		"images/aguila-sheet1.png",
		"images/murcielago-sheet0.png",
		"images/murcielago-sheet1.png",
		"images/gaviota-sheet0.png",
		"images/gaviota-sheet1.png",
		"images/gaviota-sheet2.png",
		"images/touarriba-sheet0.png",
		"images/touarriba-sheet1.png",
		"images/touabajo-sheet0.png",
		"images/touabajo-sheet1.png",
		"images/touizquierda-sheet0.png",
		"images/touizquierda-sheet1.png",
		"images/touderecha-sheet0.png",
		"images/touderecha-sheet1.png",
		"images/button_-sheet0.png",
		"images/button_-sheet1.png",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/door-open-1.m4a",
		"media/door-open-1.ogg",
		"media/itemdestroy.m4a",
		"media/itemdestroy.ogg",
		"media/hahaha.m4a",
		"media/hahaha.ogg",
		"media/applause6.m4a",
		"media/applause6.ogg",
		"media/jugarsound.m4a",
		"media/jugarsound.ogg",
		"media/salidasound.m4a",
		"media/salidasound.ogg",
		"media/boing_.m4a",
		"media/boing_.ogg",
		"media/happy and sunny.m4a",
		"media/happy and sunny.ogg",
		"media/busy fingers.m4a",
		"media/busy fingers.ogg",
		"media/cheerful.m4a",
		"media/cheerful.ogg",
		"media/corporative inspire.m4a",
		"media/corporative inspire.ogg",
		"media/happy and weet.m4a",
		"media/happy and weet.ogg",
		"media/happy place.m4a",
		"media/happy place.ogg",
		"media/my hammock.m4a",
		"media/my hammock.ogg",
		"media/rebootge.m4a",
		"media/rebootge.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}